# Generated by Django 4.2.7 on 2024-03-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_database_canteen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='PSD',
            new_name='HSD',
        ),
    ]
